server:
  port: 8888
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_study?characterEncoding=utf8&userSSL=false
    username: study
    password: gao123456

  jpa:
    show-sql: true
    database: MYSQL
    hibernate:
      ddl-auto: update
      naming-stratety: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect


  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html

