server:
  port: 8888
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_study?characterEncoding=utf8&userSSL=false
    username: study
    password: gao123456
